In [3]:
import pandas as pd

data = pd.read_csv("jobs.csv")
data

,id,job_descript,domain,soft_skills,technical_skills
0,1,"We carry out R&D&I projects, considering them ...",NaN,Willingness to travel,"Requirements Analysis, Process Design and Mode..."
1,2,Are you a passionate Data Consultant? We have ...,NaN,"Communication skills, Intercultural skills, Te...","Ticketing Tool, Incident management tools, Exc..."
2,3,Role Description\n\nThis is a full-time on-sit...,NaN,communication,"sql, excel"
3,4,Job Overview:\n\nWe are seeking a skilled IT S...,NaN,"communication, teamwork, problem-solving, atte...","excel, linux, cloud"
4,5,About the Company\n\nCorrect Group is a dynami...,NaN,"communication, interpersonal",excel
...,...,...,...,...,...
94,95,\n\nAllSTEM Connections is currently recruitin...,NaN,None,None
95,96,About the Job:\n\nThe Cell Engineer will play ...,NaN,"communication, problem-solving, organization","excel, data analysis"
96,97,Our travel agency is searching for friendly an...,NaN,negotiation,excel
97,98,JOB SUMMARY:\n\nThe Business Analyst plays a c...,NaN,"communication, leadership, problem-solving, cr...","tableau, excel, data analysis"
98,99,Job posting may be removed earlier if the posi...,NaN,initiative,"python, java, cloud, aws, tensorflow, pytorch"

In [1]:
import pandas as pd

data = pd.read_csv("annotated_jobs.csv")
data

,id,job_descript,domain,soft_skills,technical_skills
0,1,"We carry out R&D&I projects, considering them ...",NaN,None,None
1,2,Are you a passionate Data Consultant? We have ...,NaN,"communication, collaboration, organization","excel, cloud, power bi"
2,3,Role Description\n\nThis is a full-time on-sit...,NaN,communication,"sql, excel"
3,4,Job Overview:\n\nWe are seeking a skilled IT S...,NaN,"communication, teamwork, problem-solving, atte...","excel, linux, cloud"
4,5,About the Company\n\nCorrect Group is a dynami...,NaN,"communication, interpersonal",excel
...,...,...,...,...,...
94,95,\n\nAllSTEM Connections is currently recruitin...,NaN,None,None
95,96,About the Job:\n\nThe Cell Engineer will play ...,NaN,"communication, problem-solving, organization","excel, data analysis"
96,97,Our travel agency is searching for friendly an...,NaN,negotiation,excel
97,98,JOB SUMMARY:\n\nThe Business Analyst plays a c...,NaN,"communication, leadership, problem-solving, cr...","tableau, excel, data analysis"
98,99,Job posting may be removed earlier if the posi...,NaN,initiative,"python, java, cloud, aws, tensorflow, pytorch"

In [2]:
def extended_infer_domain(text):
    text = str(text).lower()
    if any(word in text for word in ['data', 'analytics', 'machine learning']):
        return 'Data/Analytics'
    elif any(word in text for word in ['it support', 'systems', 'network']):
        return 'IT Support'
    elif any(word in text for word in ['developer', 'engineer', 'software']):
        return 'Software Development'
    elif any(word in text for word in ['project manager', 'scrum', 'agile']):
        return 'Project Management'
    elif any(word in text for word in ['consultant', 'business', 'strategy']):
        return 'Consulting'
    elif any(word in text for word in ['research linguistics', 'syntax', 'phonology']):
        return 'Linguistics'
    elif any(word in text for word in ['nlp', 'natural language', 'language models','llms' ]):
        return 'Computational Linguistics'
    elif any(word in text for word in ['election', 'policy', 'governance', 'public affairs']):
        return 'Political Science'
    elif any(word in text for word in ['marketing', 'branding', 'seo']):
        return 'Marketing'
    elif any(word in text for word in ['journalism', 'reporter', 'editor']):
        return 'Media & Journalism'
    elif any(word in text for word in ['teacher','professor', 'students']):
        return 'Education'
    elif any(word in text for word in ['finance', 'accounting', 'budget']):
        return 'Finance'
    elif any(word in text for word in ['hr', 'recruitment', 'people operations']):
        return 'Human Resources'
    elif any(word in text for word in ['legal', 'attorney', 'compliance']):
        return 'Legal'
    elif any(word in text for word in ['design', 'ux', 'ui', 'illustration']):
        return 'Design & UX'
    elif any(word in text for word in ['healthcare', 'medical', 'clinic']):
        return 'Healthcare'
    elif any(word in text for word in ['logistics', 'supply chain', 'operations']):
        return 'Logistics & Operations'
    elif any(word in text for word in ['restaurant', 'waiter', 'menu', 'cook']):
        return 'Gastronomy & Service'
    elif any(word in text for word in ['hotel', 'travel', 'touristic', 'tourism']):
        return 'Tourism'
    else:
        return 'Other'

data['domain'] = data['job_descript'].apply(extended_infer_domain)

data

,id,job_descript,domain,soft_skills,technical_skills
0,1,"We carry out R&D&I projects, considering them ...",Software Development,None,None
1,2,Are you a passionate Data Consultant? We have ...,Data/Analytics,"communication, collaboration, organization","excel, cloud, power bi"
2,3,Role Description\n\nThis is a full-time on-sit...,Data/Analytics,communication,"sql, excel"
3,4,Job Overview:\n\nWe are seeking a skilled IT S...,IT Support,"communication, teamwork, problem-solving, atte...","excel, linux, cloud"
4,5,About the Company\n\nCorrect Group is a dynami...,Data/Analytics,"communication, interpersonal",excel
...,...,...,...,...,...
94,95,\n\nAllSTEM Connections is currently recruitin...,Software Development,None,None
95,96,About the Job:\n\nThe Cell Engineer will play ...,Data/Analytics,"communication, problem-solving, organization","excel, data analysis"
96,97,Our travel agency is searching for friendly an...,Consulting,negotiation,excel
97,98,JOB SUMMARY:\n\nThe Business Analyst plays a c...,Data/Analytics,"communication, leadership, problem-solving, cr...","tableau, excel, data analysis"
98,99,Job posting may be removed earlier if the posi...,Data/Analytics,initiative,"python, java, cloud, aws, tensorflow, pytorch"